language: ruby
before_install: # for bundler 2.0+
  - gem install bundler
script: bundle exec rake $RAKE_TASK
matrix:
  include:
    # Linux - Tests and Linting
    - os: linux
      rvm: 2.6
    - os: linux
      rvm: 2.5
    - os: linux
      rvm: 2.4
    # OS X - Tests
    - os: osx
      rvm: 2.6
      env: RAKE_TASK=spec
    - os: osx
      rvm: 2.5
      env: RAKE_TASK=spec
    - os: osx
      rvm: 2.4
      env: RAKE_TASK=spec
