name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [3.2, 3.1, 3.0, 2.7, 2.6, 2.5]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Test
      run: bundle exec rake
